spring.main.allow-bean-definition-overriding: true
spring.jpa.hibernate.ddl-auto: create-drop
spring.jpa.format_sql: true
spring.jpa.properties.hibernate.format_sql: true
spring.jpa.show-sql: true
spring.liquibase.enabled: false
spring.flyway.enabled: false